Repository h2oai/sparkling-water, pull requests merged in 2019-11, with the labels that each got.

#1588 [SW-1684] Migration guide was missing several changes which are already resolved in 3.28
  doc/src/site/sphinx/migration_guide.rst
Labels: Major release

#1585 [SW-1681] Change sw version to include also patch within one h2o version
  doc/build.gradle
  doc/src/site/sphinx/deployment/sw_azure_dbc.rst
  doc/src/site/sphinx/migration_guide.rst
  gradle.properties
  gradle/release.gradle
  jenkins/Jenkinsfile-release
  jenkins/sparklingWaterPipeline.groovy
  py/build.gradle
  py/src/ai/h2o/sparkling/VersionComponents.py
  py/tests/unit/simple/test_version_components.py
Labels: Major release

#1596 [SW-1694][Separation]Rest API Based H2OContext is using H2O.CLOUD.healthy()
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
Labels: dynamic-allocation

#1595 [SW-1640][Separation] SW should be able to reconnect to a new H2O cluster
  core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextUtils.scala
  py/src/ai/h2o/sparkling/H2OContext.py
  r/src/R/h2o_context.R
Labels: dynamic-allocation

#1603 [SW-1700] sparkling-water-utils is not published to maven
  dist/build.gradle
Labels: Fix release

#1598 [SW-1693][Separation] Ensure that we handle cluster non-availabiliy in decent fashion
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
Labels: dynamic-allocation

#1604 [SW-1536] To be able to serve proxy, ensure that the worker nodes have web enabled
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
Labels: dynamic-allocation

#1597 [SW-1695][Separation] In Rest API based context, we take H2O build info from H2O object, we need to use rest api
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
Labels: dynamic-allocation

#1612 [SW-1705] Deprecate `spark.ext.h2o.client.flow.extra.http.headers`
  core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
Labels: Fix release

#1608 [SW-1534] Create proxy for H2O flow as we no longer run H2O on driver side
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextUtils.scala
Labels: dynamic-allocation

#1609 [SW-1703][Separation] Rest API endpoints does not work if the external backend enables any kind of authentification
  core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/utils/FlowCredentials.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
  py/src/ai/h2o/sparkling/H2OContext.py
Labels: dynamic-allocation

#1611 [SW-1704] Expose Extra Http Headers for H2O Nodes
  core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/utils/NodeDesc.scala
  core/src/test/scala/org/apache/spark/h2o/ConfigurationPropertiesTestSuite.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
  doc/src/site/sphinx/migration_guide.rst
  py/src/ai/h2o/sparkling/H2OConf.py
Labels: Major release

#1616 [SW-1711] Fix propagation of internal security conf in Sparkling Water
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendConf.scala
  core/src/main/scala/org/apache/spark/network/Security.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
Labels: Fix release

#1655 [SW-1747] The option "-sw_ext_backend" must be enabled when REST-based client is used
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
Labels: Major release
