Repository h2oai/sparkling-water, pull requests merged in 2019-12, with the labels that each got.

#1647 [SW-1647] Convert PySpark DataFrame to H2OFrame without Client
  core/src/main/java/org/apache/spark/h2o/JavaH2OContext.java
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
  core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalWriteConverterCtx.scala
  core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
  core/src/main/scala/org/apache/spark/h2o/converters/SupportedRDDConverter.scala
  core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtx.scala
  core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
  py/src/ai/h2o/sparkling/FrameConversions.py
  py/src/ai/h2o/sparkling/H2OContext.py
Labels: Major release, dynamic-allocation

#1657 [SW-1749] Percentiles Are Not Propagated to Metadata
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
Labels: Major release

#1659 [SW-1744] Tests for Clientless Conversion from DataFrames to H2OFrames
  py/tests/conftest.py
  py/tests/unit/with_runtime_clientless_sparkling/conftest.py
  py/tests/unit/with_runtime_clientless_sparkling/test_H2O_to_Spark_conversions.py
  py/tests/unit/with_runtime_clientless_sparkling/test_Spark_to_H2O_conversions.py
  py/tests/unit_test_utils.py
Labels: Major release, dynamic-allocation

#1660 [SW-1737] Ensure the client has full flatfile in external backend
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
Labels: Fix release

#1689 [SW-1782] Improve exception when the user is not authentification in rest api client
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/H2OClusterNotReachableException.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ProxyStarter.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/RestApiUtils.scala
  core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextUtils.scala
Labels: Major release

#1685 [SW-1724] Create UDF for Ordinal Predictions
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/OrdinalPredictionTestSuite.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPrediction.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionOrdinal.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OSupervisedMOJOModel.scala
Labels: Major release

#1692 [SW-1788] Lock cloud in case of rest api client, auto mode
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/RestApiUtils.scala
  py/tests/unit/with_runtime_clientless_sparkling/conftest.py
  py/tests/unit/with_runtime_clientless_sparkling/test_GBM.py
  py/tests/unit/with_runtime_clientless_sparkling/test_H2OContext.py
  py/tests/unit/with_runtime_clientless_sparkling/test_H2O_to_Spark_conversions.py
  py/tests/unit/with_runtime_clientless_sparkling/test_Spark_to_H2O_conversions.py
Labels: Major release

#1694 [SW-1791] Make ProxyStarter more robust
  core/src/main/scala/org/apache/spark/h2o/backends/external/ProxyStarter.scala
Labels: Major release

#1681 [SW-1775] Add security tests for the client-less approach
  py/tests/unit/with_runtime_clientless_sparkling/test_GBM.py
  py/tests/unit/with_runtime_clientless_sparkling/test_H2OContext.py
  py/tests/unit/with_runtime_clientless_sparkling/test_H2O_to_Spark_conversions.py
  py/tests/unit/with_runtime_clientless_sparkling/test_Spark_to_H2O_conversions.py
  py/tests/unit/with_runtime_clientless_sparkling/test_security.py
Labels: Major release

#1690 [SW-1783] Unify passing of authentication information
  core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/RestApiUtils.scala
  core/src/main/scala/org/apache/spark/h2o/utils/FlowCredentials.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
  doc/src/site/sphinx/migration_guide.rst
  doc/src/site/sphinx/tutorials/kerberos_auth.rst
  doc/src/site/sphinx/tutorials/ldap.rst
  py/src/ai/h2o/sparkling/H2OConf.py
  py/src/ai/h2o/sparkling/H2OContext.py
  py/tests/unit/with_runtime_clientless_sparkling/test_security.py
  r/src/R/h2o_context.R
Labels: Major release

#1700 [SW-1793] In rest api approach, auto mode, external backend keeps running even if we weren't able to authentificate
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  py/tests/unit/with_runtime_clientless_sparkling/test_security.py
Labels: Major release

#1691 [SW-1787] Obtaining nodes can be done via rest API in all cases on External backend
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalBackendUtils.scala
Labels: Major release
