Repository h2oai/sparkling-water, pull requests merged in 2019-09, with the labels that each got.

#1508 [SW-1519] Switch to single value in the predictionCol and put all the details on the detailedPredictionCol
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/BinomialPredictionTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/RegressionPredictionTestSuite.scala
  ml/src/test/scala/org/apache/spark/ml/spark/models/H2OMojoModelTest.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAnomaly.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAutoEncoder.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionClustering.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionDimReduction.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionMultinomial.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionRegression.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionUtils.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionWordEmbedding.scala
Labels: Major release

#1526 [SW-1611] Script tests are not being executed correctly - some tests are not being executed
  examples/build.gradle
  examples/pipelines/hamOrSpamMultiAlgo.script.scala
  examples/scripts/StrataAirlines.script.scala
  examples/scripts/chicagoCrimeLarge.script.scala
  examples/scripts/chicagoCrimeSmall.script.scala
  examples/scripts/chicagoCrimeSmallShell.script.scala
  examples/scripts/craigslistJobTitles.script.scala
  examples/scripts/hamOrSpam.script.scala
  examples/scripts/strata2015.script.scala
  examples/src/scriptsTest/scala/water/sparkling/scripts/ScriptsTestSuite.scala
Labels: WIP

#1529 [SW-1492][Spark-2.1] Switch minimal java version for Java 1.8
  bin/run-example.sh
  bin/run-example2.cmd
  bin/run-python-script.sh
  bin/run-sparkling.sh
  bin/run-sparkling2.cmd
  bin/sparkling-env.cmd
  bin/sparkling-env.sh
  bin/sparkling-shell
  bin/sparkling-shell2.cmd
  build.gradle
  examples/build.gradle
  gradle-spark2.1.properties
  gradle-spark2.2.properties
  gradle-spark2.3.properties
  gradle-spark2.4.properties
  gradle/bench.gradle
  gradle/itest.gradle
  gradle/sparkTest.gradle
  py/build.gradle
Labels: Major release

#1519 [SW-1532] Ability to start H2OContext from Py/R without running H2O client
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendRestApiUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
  core/src/main/scala/org/apache/spark/h2o/utils/NodeDesc.scala
  core/src/test/scala/org/apache/spark/h2o/H2OConfTestSuite.scala
  py/src/ai/h2o/sparkling/H2OContext.py
Labels: dynamic-allocation

#1545 [SW-1587] Remove deprecated getter and setter SelectBestModelDecreasing on H2OGridSearch
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
  py/src/ai/h2o/sparkling/ml/algos/H2OGridSearch.py
  py/src/ai/h2o/sparkling/ml/params/H2OGridSearchParams.py
Labels: Major release

#1532 [SW-1618] Correctly handle feature names during prediction time
  examples/pipelines/hamOrSpamMultiAlgo.script.scala
  examples/src/scriptsTest/scala/water/sparkling/scripts/ScriptsTestSuite.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgorithm.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
  py/examples/pipelines/ham_or_spam_multi_algo.py
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
Labels: Fix release

#1541 [SW-1642] Prevent sending empty partitions when converting Spark Data frame to H2OFrame
  core/src/main/scala/org/apache/spark/h2o/converters/SparkDataFrameConverter.scala
  core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
  examples/src/integTest/scala/water/sparkling/itest/local/PubDev928Suite.scala
  gradle/conf/scalastyle-config.xml
Labels: Fix release

#1542 [SW-1638] Make port 9009 configurable on Azure
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/utils/AzureDatabricksUtils.scala
  doc/src/site/sphinx/deployment/pysparkling_azure_dbc.rst
  doc/src/site/sphinx/deployment/rsparkling_azure_dbc.rst
  doc/src/site/sphinx/deployment/sw_azure_dbc.rst
Labels: Fix release

#1540 [SW-1636] Enable to specify outputCols on H2OTargetEncoder
  doc/src/site/sphinx/tutorials/sw_target_encoder.rst
  ml/src/main/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoder.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoderTestSuite.scala
  py/src/ai/h2o/sparkling/ml/features/H2OTargetEncoder.py
  py/src/ai/h2o/sparkling/ml/params/H2OTargetEncoderParams.py
  py/tests/unit/with_runtime_sparkling/test_target_encoder.py
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderBase.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/params/H2OTargetEncoderParams.scala
Labels: Major release

#1547 [SW-1641] Remove requirement for the cluster size specification
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendRestApiUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalWriteConverterCtx.scala
  core/src/main/scala/org/apache/spark/h2o/converters/WriteConverterCtxUtils.scala
  core/src/main/scala/org/apache/spark/h2o/utils/H2OContextRestAPIUtils.scala
Labels: dynamic-allocation

#1543 [SW-1631] Automatically increase client timeout on top of Azure
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/utils/AzureDatabricksUtils.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
Labels: Fix release

#1548 [SW-1645] Allow to specify kill on unhealthy cloud in case of manual cluster start of external backend
  core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
Labels: Fix release
