Repository h2oai/sparkling-water, pull requests merged in 2020-07, with the labels that each got.

#2206 [SW-2344] Fix mojo test -> H2O added a new parameter and therefore number of parameters does not match now
  py/tests/unit/with_runtime_sparkling/test_mojo.py
Labels: Fix release

#2203 [SW-2339] Expose beta_constraints on GLM
  api-generation/src/main/scala/ai/h2o/sparkling/api/generation/Runner.scala
  api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/IgnoredParameters.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/params/HasBetaConstraints.scala
  py/src/ai/h2o/sparkling/ml/params/HasBetaConstraints.py
  py/tests/unit/with_runtime_sparkling/test_glm.py
Labels: Major release

#2209 [SW-352] Flow UI Scala Repl: use paste mode to interpret commands passed through Flow UI
  core/src/test/scala/ai/h2o/sparkling/backend/api/scalainterpreter/ScalaInterpreterServletTestSuite.scala
  repl/src/main/scala/ai/h2o/sparkling/repl/BaseH2OInterpreter.scala
Labels: Fix release

#2210 [SW-1510] Fix misleading error message from incompatible Java version
  bin/sparkling-env.sh
Labels: Fix release

#2204 [SW-2278] Fix benchmarks on master branch
  benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/BenchmarkBase.scala
  benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/DKVCleaner.scala
  benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/H2OFrameToDataFrameConversionBenchmark.scala
  benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/Runner.scala
  benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/TrainAlgorithmFromH2OFrameBenchmark.scala
Labels: Major release

#2207 [SW-2345] Delete H2OFrames Produced by Algorithm Parameters
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgorithm.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OAlgoParamsBase.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/params/HasBetaConstraints.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/params/HasCalibrationDataFrame.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/params/HasPlugValues.scala
Labels: Major release

#2200 [SW-2019] Implement auto cluster start for External Backend on Kubernetes & test
  assembly/build.gradle
  benchmarks/src/main/terraform/aws/modules/emr_benchmarks_deployment/main.tf
  ci/Jenkinsfile-kubernetes
  ci/commons.groovy
  core/build.gradle
  core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
  core/src/main/scala/ai/h2o/sparkling/H2OContext.scala
  core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalH2OBackend.scala
  core/src/main/scala/ai/h2o/sparkling/backend/external/K8sExternalBackendClient.scala
  core/src/main/scala/ai/h2o/sparkling/backend/external/K8sH2OStatefulSet.scala
  core/src/main/scala/ai/h2o/sparkling/backend/external/K8sHeadlessService.scala
  core/src/main/scala/ai/h2o/sparkling/backend/external/K8sUtils.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/H2OContextExtensions.scala
  core/src/test/scala/ai/h2o/sparkling/SparkTestContext.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
  doc/src/site/sphinx/deployment/kubernetes.rst
  doc/src/site/sphinx/migration_guide.rst
  kubernetes/src/main/scala/ai/h2o/sparkling/InitTest.scala
  kubernetes/src/python/initTest.py
  kubernetes/src/terraform/aws/variables.tf
  kubernetes/src/terraform/aws/vpc.tf
  py/src/ai/h2o/sparkling/ExternalBackendConf.py
  py/src/ai/h2o/sparkling/H2OContext.py
  py/tests/integration/integ_test_utils.py
  py/tests/unit_test_utils.py
  r/src/R/ai/h2o/sparkling/ExternalBackendConf.R
Labels: Major release

#2215 [SW-2294] Base non-nightly external-backend k8s image on h2o image
  bin/build-kubernetes-images.sh
  kubernetes/build.gradle
Labels: Major release

#2214 [SW-2349] Enable leaf node assignment for H2OMOJOModel
  api-generation/src/main/scala/ai/h2o/sparkling/api/generation/Runner.scala
  doc/src/site/sphinx/deployment/load_mojo.rst
  ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/AnomalyPredictionTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/BinomialPredictionTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OGBMTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/MultinomialPredictionTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/RegressionPredictionTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/TransformSchemaTestSuite.scala
  py/src/ai/h2o/sparkling/ml/models/H2OMOJOModel.py
  py/src/ai/h2o/sparkling/ml/models/H2OMOJOSettings.py
  py/src/ai/h2o/sparkling/ml/params/H2OBaseMOJOParams.py
  py/src/ai/h2o/sparkling/ml/params/H2OCommonParams.py
  r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModel.R
  r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOSettings.R
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAnomaly.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionMultinomial.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionRegression.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOSettings.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/params/H2OBaseMOJOParams.scala
Labels: Fix release

#2219 [SW-1407][FOLLOWUP] Add missing mappings for family and distribution
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/ProblemType.scala
Labels: Major release

#2225 [SW-2355] Fix build after hive changes on H2O side
  core/build.gradle
Labels: Fix release

#2223 [SW-2166] Automatic smoke tests on DBC
  assembly/build.gradle
  ci/Jenkinsfile-databricks
  ci/Jenkinsfile-deploy-testing-infra
  ci/aws/terraform/modules/jenkins/scripts/init_jenkins.groovy
  ci/commons.groovy
  ci/databricksTests/test.py
  ci/databricksTests/test.scala
  ci/databricksTests/test_template.r
  core/build.gradle
  gradle-spark2.4.properties
  gradle-spark3.0.properties
  gradle.properties
Labels: Fix release

#2227 [SW-2357] Some tests in ml package are not being run
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/AnomalyPredictionTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/AutoEncoderPredictionTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtilsTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/TransformSchemaTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/WordEmbeddingTestSuite.scala
Labels: Fix release

#2226 [SW-2356] Fix timeout on long running Rest API commands through Proxy
  core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
  core/src/main/scala/water/webserver/jetty9/SparklingWaterJettyHelper.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
  py/src/ai/h2o/sparkling/SharedBackendConf.py
  r/src/R/ai/h2o/sparkling/SharedBackendConf.R
Labels: Fix release

#2228 [SW-2359] Remove a Notion of 'labelCol' from KMeans Documentation
  doc/src/site/sphinx/ml/sw_kmeans.rst
Labels: Fix release

#2231 [SW-2361] Throw explicit exception in case hyper parameter does not exist
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OGridSearchTestSuite.scala
Labels: Major release

#2233 [SW-2360] R tests do not fail in gradle when there is failed test
  r/build.gradle
Labels: Fix release

#2232 [SW-2364] Expose Reconstruction Mean Squared Error on AutoEncoder Prediction
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/AutoEncoderPredictionTestSuite.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAutoEncoder.scala
Labels: Major release

#2234 [SW-2362] Documentation should mention how to run examples with Spark/Sparkling Shell
  doc/src/site/sphinx/install/install_and_start.rst
Labels: Fix release

#2236 [SW-2371] Missing getWithLeafNodeAssignments() Method on MOJOModelBase In Python & R
  py/src/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.py
  r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.R
Labels: Fix release

#2237 [SW-2369] Copy Sparkling Water booklet from H2O-3 repo to Sparkling Water
  booklet/build.gradle
  booklet/src/SparklingWaterBooklet.tex
  booklet/src/bibliography.bib
  booklet/src/conf/listings.tex
  booklet/src/conf/titles.tex
  booklet/src/conf/top.tex
  booklet/src/images/DataShare.png
  booklet/src/images/Topology-external.png
  booklet/src/images/Topology-internal.png
  booklet/src/images/uc1.png
  booklet/src/images/uc2.png
  booklet/src/images/uc3.png
  booklet/src/sections/FAQ.tex
  booklet/src/sections/api.tex
  booklet/src/sections/apps.tex
  booklet/src/sections/backends.tex
  booklet/src/sections/deployment.tex
  booklet/src/sections/design.tex
  booklet/src/sections/intro.tex
  booklet/src/sections/pysparkling.tex
  booklet/src/sections/usecase.tex
  booklet/src/sections/what_is_h2o.tex
  ci/Jenkinsfile-release
  ci/sparklingWaterPipeline.groovy
  dist/build.gradle
  gradle.properties
  settings.gradle
Labels: Fix release

#2240 [SW-2358] Upgrade H2O to 3.30.0.7
  gradle.properties
Labels: Fix release

#2238 [SW-2372] Expose option used for waiting before the clouding starts in internal backend
  core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala
  core/src/main/scala/org/apache/spark/h2o/backends/internal/SpreadRDDBuilder.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
  py/src/ai/h2o/sparkling/InternalBackendConf.py
  r/src/R/ai/h2o/sparkling/InternalBackendConf.R
Labels: Fix release

#2246 [SW-2377] Double Usage of Parenthesis in H2OMOJOBase.py
  py/src/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.py
Labels: Fix release

#2243 [SW-2375] Update what is H2O section in Booklet and main tex document
  booklet/src/SparklingWaterBooklet.tex
  booklet/src/sections/what_is_h2o.tex
Labels: Fix release

#2244 [SW-2376][Booklet] Update introduction section
  booklet/src/images/use-case-1.png
  booklet/src/images/use-case-2.png
  booklet/src/images/use-case-3.png
  booklet/src/sections/intro.tex
Labels: Fix release

#2245 [SW-2378][Booklet] Update design section
  booklet/src/SparklingWaterBooklet.tex
  booklet/src/sections/backends.tex
  booklet/src/sections/calling_h2o_algos.tex
  booklet/src/sections/convert_h2o_to_spark.tex
  booklet/src/sections/creating_h2o_frame.tex
  booklet/src/sections/design.tex
  booklet/src/sections/intro.tex
  booklet/src/sections/starting.tex
Labels: Fix release, WIP

#2242 [SW-2365] Expose Reconstructed Columns on DimReduction Predictions
  api-generation/src/main/scala/ai/h2o/sparkling/api/generation/Runner.scala
  doc/src/site/sphinx/deployment/load_mojo.rst
  ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/DimReductionPredictionTestSuite.scala
  py/src/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.py
  py/src/ai/h2o/sparkling/ml/models/H2OMOJOSettings.py
  py/src/ai/h2o/sparkling/ml/params/H2OBaseMOJOParams.py
  py/src/ai/h2o/sparkling/ml/params/H2OCommonParams.py
  r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.R
  r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOSettings.R
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionDimReduction.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOSettings.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/params/H2OBaseMOJOParams.scala
Labels: Major release

#2249 [SW-2381][master] Deprecate removed XGBoost options
  doc/src/site/sphinx/migration_guide.rst
Labels: Major release

#2248 [SW-2381] Deprecate removed XGBoost options
  doc/src/site/sphinx/migration_guide.rst
  ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OXGBoostParams.scala
  py/src/ai/h2o/sparkling/ml/algos/H2OXGBoost.py
  py/src/ai/h2o/sparkling/ml/params/H2OXGBoostParams.py
Labels: Fix release

#2261 [SW-2393]Doc: Multinode Xgboost is no longer experimental in AutoML
  doc/src/site/sphinx/ml/sw_automl.rst
Labels: Fix release

#2260 [SW-2392] Fix typos in the documentation
  doc/src/site/sphinx/configuration/memory_setup.rst
  doc/src/site/sphinx/deployment/aws_emr.rst
  doc/src/site/sphinx/deployment/aws_emr_edge_node.rst
  doc/src/site/sphinx/deployment/azure_hdi.rst
  doc/src/site/sphinx/deployment/backends.rst
  doc/src/site/sphinx/deployment/kubernetes.rst
  doc/src/site/sphinx/deployment/load_mojo.rst
  doc/src/site/sphinx/deployment/load_mojo_pipeline.rst
  doc/src/site/sphinx/deployment/pysparkling_azure_dbc.rst
  doc/src/site/sphinx/deployment/pysparkling_pipeline.rst
  doc/src/site/sphinx/deployment/rsparkling_azure_dbc.rst
  doc/src/site/sphinx/deployment/rsparkling_on_windows.rst
  doc/src/site/sphinx/deployment/sw_azure_dbc.rst
  doc/src/site/sphinx/deployment/terraform_emr.rst
  doc/src/site/sphinx/design/basic_primitives.rst
  doc/src/site/sphinx/design/data_sharing.rst
  doc/src/site/sphinx/design/design.rst
  doc/src/site/sphinx/design/spark_h2o_mapping.rst
  doc/src/site/sphinx/design/supported_platforms.rst
  doc/src/site/sphinx/devel/build.rst
  doc/src/site/sphinx/devel/integ_tests.rst
  doc/src/site/sphinx/devel/rest_api/scala_interpreter_endpoints.rst
  doc/src/site/sphinx/devel/running_examples.rst
  doc/src/site/sphinx/devel/unit_tests.rst
  doc/src/site/sphinx/install/install_and_start.rst
  doc/src/site/sphinx/ml/binary_model.rst
  doc/src/site/sphinx/ml/shap_values.rst
  doc/src/site/sphinx/ml/sw_automl.rst
  doc/src/site/sphinx/ml/sw_drf.rst
  doc/src/site/sphinx/ml/sw_glrm.rst
  doc/src/site/sphinx/ml/sw_grid.rst
  doc/src/site/sphinx/ml/sw_kmeans.rst
  doc/src/site/sphinx/ml/sw_target_encoder.rst
  doc/src/site/sphinx/ml/sw_xgboost.rst
  doc/src/site/sphinx/pysparkling.rst
  doc/src/site/sphinx/rsparkling.rst
  doc/src/site/sphinx/tutorials/change_default_port.rst
  doc/src/site/sphinx/tutorials/h2oframe_as_data_source.rst
  doc/src/site/sphinx/tutorials/hive_support.rst
  doc/src/site/sphinx/tutorials/import_export_s3.rst
  doc/src/site/sphinx/tutorials/kerberized_cluster.rst
  doc/src/site/sphinx/tutorials/logs.rst
  doc/src/site/sphinx/tutorials/run_sparkling_water.rst
  doc/src/site/sphinx/tutorials/secured_flow.rst
  doc/src/site/sphinx/tutorials/spark_h2o_conversions.rst
  doc/src/site/sphinx/tutorials/ssl.rst
Labels: Fix release

#2251 [SW-1847] Automatically Document Sparkling Water Algo API
  .gitignore
  api-generation/src/main/scala/ai/h2o/sparkling/api/generation/scala/ParametersTemplate.scala
  build.gradle
  doc/build.gradle
  doc/src/main/scala/ai/h2o/sparkling/doc/generation/ParametersTemplate.scala
  doc/src/main/scala/ai/h2o/sparkling/doc/generation/ParametersTocTreeTemplate.scala
  doc/src/main/scala/ai/h2o/sparkling/doc/generation/Runner.scala
  doc/src/main/scala/ai/h2o/sparkling/doc/generation/SubstitutionContext.scala
  doc/src/site/sphinx/index.rst
  doc/src/site/sphinx/ml/sw_automl.rst
  doc/src/site/sphinx/ml/sw_drf.rst
  doc/src/site/sphinx/ml/sw_glrm.rst
  doc/src/site/sphinx/ml/sw_grid.rst
  doc/src/site/sphinx/ml/sw_kmeans.rst
  doc/src/site/sphinx/ml/sw_target_encoder.rst
  doc/src/site/sphinx/ml/sw_xgboost.rst
  scoring/src/main/scala/ai/h2o/sparkling/ml/params/H2OTargetEncoderMOJOParams.scala
Labels: Major release

#2265 [SW-2395] Automatically generate the configuration table in documentation
  .gitignore
  core/src/main/scala/ai/h2o/sparkling/H2OConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala
  doc/build.gradle
  doc/src/main/scala/ai/h2o/sparkling/doc/generation/ConfigurationRunner.scala
  doc/src/main/scala/ai/h2o/sparkling/doc/generation/ConfigurationsTemplate.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
Labels: Major release

#2266 [SW-329] Sparkling Water UI in Spark should show explanation of properties
  core/src/main/scala/ai/h2o/sparkling/H2OContext.scala
  core/src/main/scala/ai/h2o/sparkling/backend/internal/InternalBackendConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/H2OContextExtensions.scala
  core/src/main/scala/org/apache/spark/h2o/ui/H2OContextStartedEvent.scala
  core/src/main/scala/org/apache/spark/h2o/ui/SparklingWaterInfoPage.scala
  core/src/main/scala/org/apache/spark/h2o/ui/SparklingWaterInfoProvider.scala
  core/src/main/scala_spark_2.1/org/apache/spark/h2o/ui/SparklingWaterListener.scala
  core/src/main/scala_spark_2.2/org/apache/spark/h2o/ui/SparklingWaterListener.scala
  core/src/main/scala_spark_2.3/org/apache/spark/h2o/ui/AppStatusListener.scala
  core/src/main/scala_spark_2.3/org/apache/spark/h2o/ui/AppStatusStore.scala
  core/src/main/scala_spark_others/org/apache/spark/h2o/ui/AppStatusListener.scala
  core/src/main/scala_spark_others/org/apache/spark/h2o/ui/AppStatusStore.scala
Labels: Major release
