Repository h2oai/sparkling-water, pull requests merged in 2020-04, with the labels that each got.

#2013 [SW-2147] Add spotless check for ending new lines for most of the other files (the other files do not have better formattes now)
  apps/streaming/socket_send_spark.py
  bin/launch-spark-cloud.sh
  bin/run-example.sh
  bin/run-python-script.sh
  bin/run-sparkling.sh
  build.gradle
  core/src/test/resources/log4j.properties
  doc/src/site/sphinx/extensions/contentui/__init__.py
  docker/bin/common.sh
  docker/bin/run-example.sh
  docker/build.sh
  docker/sparkling-water/build.sh
  gradle/publish/closeBucket.sh
  gradle/publish/createStagingId.sh
  gradle/publish/uploadToNexus.sh
  jenkins/docker/conf/yarn-site.xml
  jenkins/sparklingWaterPipeline.groovy
  ml/src/test/resources/log4j.properties
  ml/src/test/resources/mojo2data/run_example.sh
  py/examples/ChicagoCrimeDemo.py
  py/examples/tests/pysparkling_ml_import_overrides_spark_test.py
  py/src/ai/h2o/sparkling/ml/H2OStageBase.py
  py/src/setup.py
  r/src/.Rbuildignore
  r/src/LICENSE
  r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOSettings.R
  templates/src/terraform/aws/modules/emr/outputs.tf
  templates/src/terraform/aws/modules/emr_security/emr_ec2_role.tf
  templates/src/terraform/aws/modules/network/main.tf
Labels: Major release

#1956 [SW-1779] Change Spark DataFrame to H2OFrame Conversion to Implicitly Convert String Columns to Categoricals
  core/src/main/scala/ai/h2o/sparkling/backend/H2OChunk.scala
  core/src/main/scala/ai/h2o/sparkling/backend/H2ODataFrame.scala
  core/src/main/scala/ai/h2o/sparkling/backend/H2ORDD.scala
  core/src/main/scala/ai/h2o/sparkling/backend/Writer.scala
  core/src/main/scala/ai/h2o/sparkling/backend/converters/CategoricalDomainBuilder.scala
  core/src/main/scala/ai/h2o/sparkling/backend/converters/CategoricalPreviewWriter.java
  core/src/main/scala/ai/h2o/sparkling/backend/converters/DataTypeConverter.scala
  core/src/main/scala/ai/h2o/sparkling/backend/converters/SparkDataFrameConverter.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/ConversionUtils.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/RestCommunication.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/SupportedTypes.scala
  core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterTestSuite.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/CollectCategoricalDomainsTask.java
  extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/LocalNodeDomains.java
  extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/UpdateCategoricalIndicesTask.java
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ChunkCategoricalDomainsServlet.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ChunkServlet.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ImportFrameHandler.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/Paths.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/ServletBase.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/SparklingWaterServletProvider.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/ChunkAutoBufferReader.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/ChunkAutoBufferWriter.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/ChunkSerdeConstants.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/serde/SerdeUtils.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OKMeansTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/features/H2OTargetEncoderTestSuite.scala
  py/tests/unit/with_runtime_sparkling/test_Spark_to_H2O_conversions.py
  r/src/tests/testthat/testConversions.R
Labels: Major release

#2014 [SW-2149] Remove missleading comment in R's namespace file.
  r/src/NAMESPACE
Labels: Major release

#2015 [SW-2150] Remove subproject apps-streaming
  apps/streaming/README.rst
  apps/streaming/build.gradle
  apps/streaming/socket_send_spark.py
  apps/streaming/src/main/scala/ai/h2o/PipelineDemo.scala
  apps/streaming/src/main/scala/ai/h2o/RandomEvent.scala
  build.gradle
  settings.gradle
Labels: Major release

#2000 [SW-2120][backport-3.28.1] Enable H2O to Connect to Hive
  core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalH2OBackend.scala
  core/src/main/scala/ai/h2o/sparkling/backend/shared/ArgumentBuilder.scala
  core/src/main/scala/ai/h2o/sparkling/backend/shared/SharedBackendConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/shared/SharedBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/internal/H2ORpcEndpoint.scala
  core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
  py/src/ai/h2o/sparkling/SharedBackendConf.py
  r/src/R/ai/h2o/sparkling/SharedBackendConf.R
Labels: Fix release

#1991 [SW-2120] Enable H2O to Connect to Hive
  core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalH2OBackend.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/SharedBackendUtils.scala
  core/src/main/scala/org/apache/spark/h2o/backends/internal/H2ORpcEndpoint.scala
  core/src/main/scala/org/apache/spark/h2o/backends/internal/InternalH2OBackend.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
  doc/src/site/sphinx/migration_guide.rst
  py/src/ai/h2o/sparkling/SharedBackendConf.py
  r/src/R/ai/h2o/sparkling/SharedBackendConf.R
Labels: Major release

#2017 [SW-2144] Don't setup dependency on pyspark & numpy
  doc/src/site/sphinx/pysparkling.rst
  py/src/setup.py
Labels: Fix release

#2011 [SW-2145] Fix initialization of Sparkling Water JAR in case we call import pysparkling and sc is not yet running
  py/examples/tests/pySparklingImportBeforeSparkSessionCreated.py
  py/src/ai/h2o/sparkling/Initializer.py
  py/tests/unit/simple/test_pyspark_submit_args.py
Labels: Fix release

#2010 [SW-2143] bin/build-kubernetes-images.sh should get spark version from $SPARK_HOME directory
  bin/build-kubernetes-images.sh
  bin/sparkling-env.sh
  kubernetes/build.gradle
Labels: Fix release

#1988 [SW-2118] Deprecate and Disable allStringColumnsToCategorical Option
  core/src/test/scala/ai/h2o/sparkling/H2OFrameTestSuite.scala
  doc/src/site/sphinx/migration_guide.rst
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAlgoCommonUtils.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OKMeans.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala
  py/src/ai/h2o/sparkling/ml/params/H2OCommonParams.py
Labels: Major release

#2020 [SW-2155] Upgrade H2O to 3.30.0.1
  gradle.properties
Labels: Major release

#2019 [SW-2120][FOLLOWUP] Refresh Tokens When Using External Backend
  core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalH2OBackend.scala
Labels: Fix release

#2021 Revert "[SW-2119] Make SW Compatible with Older Versions of Steam (#1989)"
  dist/build.gradle
Labels: Fix release

#2023 [SW-1779][FOLLOWUP] Remove java doc warnings in LocalNodeDomains
  extensions/src/main/scala/ai/h2o/sparkling/extensions/internals/LocalNodeDomains.java
Labels: Major release

#2029 [SW-2088] ]Remove deprecated MetricsSupport
  core/src/main/scala/water/support/ModelMetricsSupport.scala
Labels: Major release

#2028 [SW-2085] Remove deprecated DeepLearningSupport and GBMSupport
  core/src/main/scala/water/support/DeepLearningSupport.scala
  core/src/main/scala/water/support/GBMSupport.scala
Labels: Major release

#2027 [SW-2083] Remove deprecated hex.ModelUtils
  core/src/main/scala/hex/ModelUtils.scala
Labels: Major release

#2030 [SW-2134] Remove deprecated H2OFrameSupport
  core/src/main/scala/water/support/H2OFrameSupport.scala
Labels: Major release

#2031 [SW-2136] Remove deprecated JoinSupport
  core/src/main/scala/water/munging/JoinMethod.java
  core/src/main/scala/water/support/JoinSupport.scala
Labels: Major release

#2032 [SW-2140] Remove deprecated model serialization support
  core/src/main/scala/water/support/ModelSerializationSupport.scala
Labels: Major release

#2025 [SW-1971] Remove deprecated method H2OContext.getOrCreate with sparkSession or SparkContext argument
  core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/JavaH2OContext.java
  py/src/ai/h2o/sparkling/H2OContext.py
  r/src/R/ai/h2o/sparkling/H2OContext.R
Labels: Major release

#2026 [SW-2074] Remove Implicit Switch to External Backend when H2OConf.setH2OCluster is called
  core/src/main/scala/ai/h2o/sparkling/backend/external/ExternalBackendConf.scala
  py/src/ai/h2o/sparkling/ExternalBackendConf.py
  r/src/R/ai/h2o/sparkling/ExternalBackendConf.R
Labels: Major release

#2033 [SW-2128] Remove deprecated allStringColumnsToCategorical
  core/src/main/scala/ai/h2o/sparkling/H2OFrame.scala
  doc/src/site/sphinx/migration_guide.rst
  ml/src/main/scala/ai/h2o/sparkling/ml/params/H2OCommonParams.scala
  py/src/ai/h2o/sparkling/ml/algos/H2OAutoML.py
  py/src/ai/h2o/sparkling/ml/algos/H2ODRF.py
  py/src/ai/h2o/sparkling/ml/algos/H2ODeepLearning.py
  py/src/ai/h2o/sparkling/ml/algos/H2OGBM.py
  py/src/ai/h2o/sparkling/ml/algos/H2OGLM.py
  py/src/ai/h2o/sparkling/ml/algos/H2OGridSearch.py
  py/src/ai/h2o/sparkling/ml/algos/H2OKMeans.py
  py/src/ai/h2o/sparkling/ml/algos/H2OXGBoost.py
  py/src/ai/h2o/sparkling/ml/params/H2OCommonParams.py
Labels: Major release

#2036 [SW-2164] Fix class not found org.spark_project.jetty.util.thread.ThreadPool error
  core/src/main/scala/ai/h2o/sparkling/backend/utils/ProxyStarter.scala
Labels: Fix release

#2039 [SW-2170] Update description of spark.ext.h2o.external.cluster.size in SW Documentation
  doc/src/site/sphinx/configuration/configuration_properties.rst
  doc/src/site/sphinx/deployment/backends.rst
Labels: Fix release

#2038 [SW-2169] Add numpy to Python Kubernetes Image
  kubernetes/build.gradle
Labels: Fix release

#2040 [SW-2172] Shadow scala-compat introduced transitively from xgboost 1.0
  assembly/build.gradle
Labels: Fix release

#2045 [SW-2175] getFeaturesCols in python returns scala obj
  py/src/ai/h2o/sparkling/ml/models/H2OMOJOModelBase.py
Labels: Fix release

#2048 [SW-2174] Don't do version check in case user is using databricks-connect
  py/src/ai/h2o/sparkling/Initializer.py
Labels: Fix release

#2049 [SW-2172][FOLLOWUP] shadow only scala.compat.java8 and scala.concurrent.java8
  assembly/build.gradle
  extensions/build.gradle
Labels: Fix release

#2046 [SW-2177] Context Path is Erased From Rest Calls
  core/src/main/scala/ai/h2o/sparkling/backend/utils/RestCommunication.scala
Labels: Fix release

#2047 [SW-2176] Expose spark.ext.h2o.allow_insecure_xgboost parameter
  core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/SharedBackendUtils.scala
  doc/src/site/sphinx/configuration/configuration_properties.rst
  py/src/ai/h2o/sparkling/SharedBackendConf.py
  r/src/R/ai/h2o/sparkling/SharedBackendConf.R
Labels: Fix release

#2052 [SW-2181] Context Path Must be Also Considered on H2O Worker Nodes
  core/src/main/scala/ai/h2o/sparkling/backend/utils/SharedBackendUtils.scala
Labels: Fix release

#2051 [SW-2090] Set log level via rest API
  core/src/main/scala/ai/h2o/sparkling/backend/utils/LogUtil.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/RestApiUtils.scala
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  extensions/src/main/resources/META-INF/services/water.api.Schema
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/LogLevelHandler.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/Paths.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/SparklingWaterRestApiHandlersRegister.scala
  extensions/src/main/scala/ai/h2o/sparkling/extensions/rest/api/schema/LogLevelV3.java
  py/src/ai/h2o/sparkling/H2OContext.py
  r/src/R/ai/h2o/sparkling/H2OContext.R
Labels: Major release

#2054 [SW-2179] Deprecate setH2OClientLogLevel and setH2ONodeLogLevel methods
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  doc/src/site/sphinx/migration_guide.rst
Labels: Fix release

#2055 [SW-2180] Remove deprecated setH2OClientLogLevel and setH2ONodeLogLevel method
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
Labels: Major release

#2053 [SW-2172][FOLLOWUP] Fix build of Benchmarks subproject
  benchmarks/build.gradle
  core/build.gradle
  examples/build.gradle
Labels: Fix release

#2058 [SW-2168] The AWS java sdk s3 in SW throws the exception: java.lang.IllegalStateException: Socket not created by this factory.
  assembly/build.gradle
Labels: Fix release

#2057 [SW-2182] Document How to Import Hive Data in Kerberized Environment
  doc/src/site/sphinx/tutorials/hive_support.rst
Labels: Fix release

#2063 [SW-2187] Remove flows from SW repo
  examples/build.gradle
  examples/flows/2016_H2O_Tour_Chicago.flow
  examples/flows/Amazon_Fine_Food_Sentiment_Analysis.flow
  examples/flows/DataSourceAPI_Example.flow
  examples/flows/Ham_Or_Spam_Pipeline.flow
  examples/flows/Lending_Club.flow
  examples/flows/Strata_SJ_2016.flow
  examples/flows/index.list
Labels: Major release

#2061 [SW-2044] Introduce method asSparkFrame on H2OContext.scala and deprecate asDataFrame
  benchmarks/src/main/scala/ai/h2o/sparkling/benchmarks/H2OFrameToDataFrameConversionBenchmark.scala
  core/src/integTest/scala/ai/h2o/sparkling/IntegrationTestSuite.scala
  core/src/integTest/scala/ai/h2o/sparkling/internal/H2OContextConversionOnSubsetExecutors.scala
  core/src/main/scala/ai/h2o/sparkling/H2OFrame.scala
  core/src/main/scala/ai/h2o/sparkling/backend/api/h2oframes/H2OFramesHandler.scala
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/JavaH2OContext.java
  core/src/test/scala/ai/h2o/sparkling/ConfigurationPropertiesTestSuite.scala
  core/src/test/scala/ai/h2o/sparkling/H2OFrameTestSuite.scala
  core/src/test/scala/ai/h2o/sparkling/backend/api/dataframes/DataFramesHandlerTestSuite.scala
  core/src/test/scala/ai/h2o/sparkling/backend/api/scalainterpreter/ScalaCodeHandlerTestSuite.scala
  core/src/test/scala/ai/h2o/sparkling/backend/converters/DataExchangeTestSuite.scala
  core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterTestSuite.scala
  core/src/test/scala/ai/h2o/sparkling/backend/converters/SupportedRDDConverterTestSuite.scala
  doc/src/site/sphinx/deployment/use_on_zeppelin.rst
  doc/src/site/sphinx/devel/integ_tests.rst
  doc/src/site/sphinx/migration_guide.rst
  doc/src/site/sphinx/tutorials/shap_values.rst
  doc/src/site/sphinx/tutorials/spark_h2o_conversions.rst
  doc/src/site/sphinx/tutorials/sw_automl.rst
  doc/src/site/sphinx/tutorials/sw_drf.rst
  doc/src/site/sphinx/tutorials/sw_kmeans.rst
  doc/src/site/sphinx/tutorials/sw_target_encoder.rst
  doc/src/site/sphinx/tutorials/sw_xgboost.rst
  ml/src/main/scala/ai/h2o/sparkling/ml/models/H2OTargetEncoderModel.scala
  py/src/ai/h2o/sparkling/H2OContext.py
  r/src/R/ai/h2o/sparkling/H2OContext.R
Labels: Fix release

#2062 [SW-2186] Remove asDataFrame method
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
  core/src/main/scala/org/apache/spark/h2o/JavaH2OContext.java
Labels: Major release

#2060 [SW-2091] Import Hive table over rest
  core/src/main/scala/ai/h2o/sparkling/backend/utils/H2OContextExtensions.scala
  doc/src/site/sphinx/tutorials/hive_support.rst
  py/src/ai/h2o/sparkling/H2OContext.py
  r/src/R/ai/h2o/sparkling/H2OContext.R
Labels: Major release

#2068 [SW-2168][FollowUp] The AWS java sdk s3 in SW throws the exception: java.lang.IllegalStateException
  assembly/build.gradle
Labels: Fix release

#2072 [SW-2160][FollowUp] Fix interrmitent error coming from sparkyr
  r/src/tests/testthat/testConversions.R
Labels: WIP
