Repository h2oai/sparkling-water, pull requests merged in 2021-02, with the labels that each got.

#2446 [SW-2523] Remove Documentation Badge From Redme.md
  README.rst
Labels: Fix release

#2447 [SW-2524] Upgrade Links in readme.md to Documentation for Spark 3.0
  README.rst
Labels: Fix release

#2449 [SW-2521] Upgrade to H2O 3.32.0.4
  gradle.properties
Labels: Fix release

#2452 [SW-2522] Docs: Add licensing information
  doc/src/site/sphinx/about.rst
Labels: Major release, docs

#2456 [SW-2447] Remove Deprecation of `getTrainingParams` on H2OMOJOModel
  booklet/src/sections/productionazing.tex
  doc/src/site/sphinx/migration_guide.rst
  py-scoring/src/ai/h2o/sparkling/ml/params/H2OMOJOModelParams.py
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
Labels: Major release

#2460 [SW-2529] Fix Imports in Documentation Sample for Pipeline MOJO
  doc/src/site/sphinx/deployment/load_mojo_pipeline.rst
Labels: Fix release

#2463 [SW-2526] Upgrade H2O Test Image to Version 84
  ci/docker/Jenkinsfile-build-docker
Labels: Fix release

#2464 [SW-2526][FOLLOWUP] Upgrade H2O Test Image to Version 84
  ci/build.gradle
Labels: Fix release

#2455 [SW-2471] Extend H2O Client Deprecations to 3.36
  core/src/main/scala/org/apache/spark/h2o/H2OConf.scala
  core/src/main/scala/org/apache/spark/h2o/H2OContext.scala
Labels: Major release

#2461 [SW-2530] Enable Beta Constraints Tests On H2OGAM and H2OGLM
  py/tests/unit/with_runtime_sparkling/test_gam.py
  py/tests/unit/with_runtime_sparkling/test_glm.py
Labels: Fix release

#2465 [SW-2460][FOLLOWUP] Fix Compilation of CoxPH Documentation
  doc/src/site/sphinx/ml/sw_coxph.rst
Labels: Major release
