Repository h2oai/sparkling-water, pull requests merged in 2021-12, with the labels that each got.

#2684 [SW-2654] Remove Invalid Parameters from DAI MOJO Documentation
  doc/src/site/sphinx/deployment/load_mojo_pipeline.rst
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPipelineModel.scala
Labels: 3.34.0.5-1

#2686 [SW-2652][FOLLOWUP] Add more items to roadmap for Q1-2022
  README.rst
Labels: 3.34.0.5-1

#2687 [SW-2657] Add example of structured streaming application
  examples/src/main/scala/ai/h2o/sparkling/examples/CraigslistJobTitlesStructuredStreamingApp.scala
Labels: 3.34.0.5-1

#2677 [SW-2564] Fix and update tutorial for GCP Dataproc
  doc/src/site/sphinx/deployment/sw_google_cloud_dataproc.rst
Labels: 3.34.0.5-1

#2689 [SW-2659] Upgrade to H2O 3.34.0.5
  gradle.properties
Labels: 3.34.0.5-1

#2691 [SW-2660] Use pypandoc 1.6.4 during Execution of Tests
  py-scoring/build.gradle
  py/build.gradle
Labels: 3.34.0.5-1

#2682 [SW-2637] Add progress bar
  core/src/main/scala/ai/h2o/sparkling/H2OFrame.scala
  core/src/main/scala/ai/h2o/sparkling/backend/H2OJob.scala
  core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/H2OContextExtensions.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/ProgressBar.scala
  core/src/test/scala/ai/h2o/sparkling/H2OConfTestSuite.scala
  core/src/test/scala/ai/h2o/sparkling/backend/utils/ProgressBarTestSuite.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/utils/EstimatorCommonUtils.scala
Labels: 3.36.0.1-1

#2695 [SW-2662] Increase Timeout for SW CI Pipelines to 10h
  ci/sparklingWaterPipeline.groovy
Labels: 3.36.0.1-1

#2688 [SW-2645] Treat Spark Boolean type as Categorical type within H20 frame.
  core/src/main/scala/ai/h2o/sparkling/backend/Writer.scala
  core/src/main/scala/ai/h2o/sparkling/backend/converters/DataTypeConverter.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/ReflectionUtils.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/SupportedTypes.scala
  core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterFullCategoricalTestSuite.scala
  core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterTestSuite.scala
  doc/src/site/sphinx/design/spark_h2o_mapping.rst
  doc/src/site/sphinx/migration_guide.rst
  py/tests/unit/with_runtime_sparkling/test_Spark_to_H2O_conversions.py
  r/src/tests/testthat/testConversions.R
Labels: 3.36.0.1-1

#2706 [SW-2672] Upgrade to H2O 3.36.0.1
  gradle.properties
Labels: Major release, 3.36.0.1-1
