Repository h2oai/sparkling-water, pull requests merged in 2022-01, with the labels that each got.

#2709 [SW-2665] Updated Scala/Python example of RuleFit usage.
  doc/src/site/sphinx/ml/shap_values.rst
  doc/src/site/sphinx/ml/sw_auto_encoder.rst
  doc/src/site/sphinx/ml/sw_automl.rst
  doc/src/site/sphinx/ml/sw_deep_learning.rst
  doc/src/site/sphinx/ml/sw_drf.rst
  doc/src/site/sphinx/ml/sw_gam.rst
  doc/src/site/sphinx/ml/sw_glrm.rst
  doc/src/site/sphinx/ml/sw_grid.rst
  doc/src/site/sphinx/ml/sw_isolation_forest.rst
  doc/src/site/sphinx/ml/sw_kmeans.rst
  doc/src/site/sphinx/ml/sw_pca.rst
  doc/src/site/sphinx/ml/sw_rule_fit.rst
  doc/src/site/sphinx/ml/sw_target_encoder.rst
  doc/src/site/sphinx/ml/sw_xgboost.rst
Labels: 3.36.0.1-1

#2700 [SW-2670] Fix Databricks Smoke Tests
  ci/Jenkinsfile-databricks
Labels: 3.36.0.1-1

#2707 [SW-2673] Fix ChicagoCrimeApp example not working
  examples/src/main/scala/ai/h2o/sparkling/examples/ChicagoCrimeApp.scala
  ml/src/test/resources/airlines_boolean.mojo
  ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OMOJOModelTestSuite.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/RowConverter.scala
Labels: 3.36.0.1-1

#2711 [SW-2676] Change Domain Levels to "True" and "False" for Columns Originating in BooleanType
  core/src/main/scala/ai/h2o/sparkling/backend/Writer.scala
  core/src/main/scala/ai/h2o/sparkling/backend/utils/ReflectionUtils.scala
  core/src/test/scala/ai/h2o/sparkling/backend/converters/DataFrameConverterTestSuite.scala
  doc/src/site/sphinx/design/spark_h2o_mapping.rst
  doc/src/site/sphinx/migration_guide.rst
  py/tests/unit/with_runtime_sparkling/test_Spark_to_H2O_conversions.py
  r/src/tests/testthat/testConversions.R
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/RowConverter.scala
Labels: 3.36.0.1-1

#2710 [SW-2675] Upgrade Sparkling Water Snapshot Version to 3.38.0.1-1-SNAPSHOT
  gradle.properties
Labels: 3.38.0.1-1

#2705 [SW-2664] Expose "cv_scoring_history" on H2OMOJOModel
  ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OMOJOModelTestSuite.scala
  py-scoring/src/ai/h2o/sparkling/ml/params/H2OMOJOModelParams.py
  py-scoring/src/ai/h2o/sparkling/ml/params/H2OTypeConverters.py
  py/tests/unit/with_runtime_sparkling/test_mojo.py
  r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModel.R
  r/src/tests/testthat/testMojo.R
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/params/NullableDataFrameArrayParam.scala
Labels: 3.36.0.2-1

#2717 [SW-2679] Add Release Notes for Release 3.34.0.8-1
  doc/CHANGELOG.rst
Labels: 3.36.0.2-1

#2715 [SW-2635] Model summary after training - basic version without html
  core/src/main/scala/ai/h2o/sparkling/backend/SharedBackendConf.scala
  core/src/test/scala/ai/h2o/sparkling/H2OConfTestSuite.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OAutoML.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OEstimator.scala
  ml/src/main/scala/ai/h2o/sparkling/ml/algos/H2OGridSearch.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OMOJOModelTestSuite.scala
  py-scoring/src/ai/h2o/sparkling/ml/params/H2OMOJOModelParams.py
  py/tests/unit/with_runtime_sparkling/test_mojo.py
  r/src/R/ai/h2o/sparkling/ml/models/H2OMOJOModel.R
  r/src/tests/testthat/testMojo.R
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
Labels: 3.36.0.2-1

#2713 [SW-2677] Make unwrapMojoModel() Independent on Spark Runtime
  ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OMOJOModelSparkRuntimeIndependencyTestSuite.scala
  ml/src/test/scala/ai/h2o/sparkling/ml/models/H2OMOJOModelTestSuite.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OAlgorithmMOJOModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OAutoEncoderMOJOBase.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2ODimReductionMOJOModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OGLRMMOJOBase.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOBaseCache.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPipelineModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPrediction.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionAnomaly.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionBinomial.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionClustering.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionCoxPH.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionDimReduction.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionMultinomial.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionOrdinal.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionRegression.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOPredictionWordEmbedding.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OMOJOReader.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OSupervisedMOJOModel.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/H2OWord2VecMOJOBase.scala
  scoring/src/main/scala/ai/h2o/sparkling/ml/models/HasMojo.scala
Labels: 3.36.0.2-1

#2719 [SW-2681] Add Comment to Documentation about Contributions Support only in Binomial and Regression Models
  doc/src/site/sphinx/deployment/load_mojo.rst
Labels: 3.36.0.2-1
